### ISSUE TITLE
why steelworks standard

### ISSUE THREAD

**Issue by uujuju1** [THCworkshopCN/THC-Industry#3]
when i did the pr i made steelworks standard into steelworks advanced but i forgot to delete the old file
eclipse forked the repo and it didnt work

**Comment by Eclipse-04** [comment]
:)
i already fixed it somehow
i thought it was a stuff inside the mod

**Comment by BHLuotianyi** [comment]
_Comment edited._
You can just try to build a standard steelworks ingame.
[Cooling station-water](https://github.com/THCworkshopCN/THC-Industry/blob/dev/content/blocks/effect/cooling-station-water.hjson)
[Irom quantifier](https://github.com/THCworkshopCN/THC-Industry/blob/dev/content/blocks/effect/material-entering-iron.hjson)
[Standard steelworks](https://github.com/THCworkshopCN/THC-Industry/blob/dev/content/blocks/multi-block/crafting/steelworks-standard.hjson)
These three things should be placed together (or connected with conveyors) in order to let the factory work.That's why [Standard steelworks](https://github.com/THCworkshopCN/THC-Industry/blob/dev/content/blocks/multi-block/crafting/steelworks-standard.hjson) is placed in a fileholder called [multi-block](https://github.com/THCworkshopCN/THC-Industry/tree/dev/content/blocks/multi-block)
Multi-block buildings (probably mainly factories) will be the _creative_ part of THC.
The more complicated (high-level) the building is,the more blocks should be put together for the multi-block building.
E.g :  A big uranium reactor needs at least : 
Cooling staion ,Fuel-inputter ,Safety center ,Controlling station ,Steam turbine.
Why don't we put them in ONE huge block?
1.To make the mod content more interesting
2.Imagine :
**A** reactor certainly needs **a** controlling station.But **1** controlling staion is also enough for **5** reactors.
A power station **that burns coal** may just need **1 steam turbine** .But a **nuclear fusion** power station may needs **100**,isn't it?
And I think that it is something that is _**Mindustry-style**_
_hope you can understand what the hel im saying_

**Comment by Eclipse-04** [comment]
~~i thought it was a multicrafter~~
also, ~~should i pr a multi-crafter?~~
